name: Deploy Portfolio to S3

# on:
#   push:
#     branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::949530157299:role/thestackdev-dev-github_actions
          aws-region: ap-south-1
          role-session-name: GitHubActionsSession

      - name: Sync to S3
        run: aws s3 sync out/ s3://thestackdev-portfolio-dev --delete
